app/app/urls.py
from django.contrib import admin
from django.urls import path

from web.views import HomeView, EntryFormView, CSVUploaderView

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('entries/', EntryFormView.as_view(), name="entries"),
    path('csv_upload/', CSVUploaderView.as_view(), name="csv_uploader"),
    path('admin/', admin.site.urls),
]

assignment/core/urls.py
from django.conf.urls import url

from .views import HomeView, FileUploadView, EntryFormView
from .api_views import EntryFormAPIView

app_name = 'core'

urlpatterns = [
    # api urls
    url(r'^api/entry/$', EntryFormAPIView.as_view(), name='api-entry'),

    # django view urls
    url(r'^upload/$', FileUploadView.as_view(), name='upload'),
    url(r'^entry/$', EntryFormView.as_view(), name='entry'),
    url(r'^home/$', HomeView.as_view(), name='home'),
    url(r'', HomeView.as_view(), name='index'),
]

assignment/datapane/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('core.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mpa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fe_challenge.urls')),
]

assignment/backend/datapane/core/models.py
from django.db import models
from django.core.validators import FileExtensionValidator

# Create your models here.
def get_file_path(instance, filename):
    return '{}'.format(filename)

class FileUpload(models.Model):
    csvfile = models.FileField('CSV file', upload_to=get_file_path, validators=[FileExtensionValidator(['csv'])])
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)


class EntryForm(models.Model):
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=200)
    age = models.PositiveIntegerField()

assignment/core/models.py
from django.db import models

# Create your models here.
class EntryFormModel(models.Model):
    name = models.CharField(max_length=100, null=False)
    age = models.PositiveIntegerField(null=False)
    email = models.EmailField(null=False)

assignment/core/forms.py
from django import forms


class FileUploadForm(forms.Form):
    file = forms.FileField(label='Select a CSV file', widget=forms.FileInput(attrs={'accept': '.csv'}))

assignment/backend/datapane/core/views.py
import requests

from django.http import HttpResponse, StreamingHttpResponse
from django.shortcuts import render
from django.conf import settings
from django.template import engines
from django.views.generic import TemplateView

from rest_framework.parsers import FormParser, MultiPartParser, JSONParser
from rest_framework.viewsets import ModelViewSet
from rest_framework.decorators import action

from .models import FileUpload, EntryForm
from .serializers import FileUploadSerializer, EntryFormSerializer


def index(request):
    return render(request, 'base.html')


def loremipsum(request):
    return render(request, 'index.html')

class FileUploadView(ModelViewSet):
    queryset = FileUpload.objects.all()
    serializer_class = FileUploadSerializer
    parser_classes = (MultiPartParser, FormParser,)

    def perform_create(self, serializer):
        serializer.save(csvfile=self.request.data.get('csvfile'))

    def get_queryset(self):
        queryset = FileUpload.objects.all()
        pk = self.request.query_params.get('id', None)
        if pk is not None:
            self.queryset = self.queryset.filter(pk=pk)
        return self.queryset


class EntryFormView(ModelViewSet):
    queryset = EntryForm.objects.all()
    serializer_class = EntryFormSerializer
    parser_classes = [JSONParser]


def catchall_dev(request, upstream='http://localhost:3000'):
    upstream_url = upstream + request.path
    response = requests.get(upstream_url, stream=True)
    content_type = response.headers.get('Content-Type')

    if content_type == 'text/html; charset=UTF-8':
        return HttpResponse(
            content=engines['django'].from_string(response.text).render(),
            status=response.status_code,
            reason=response.reason,
        )

    else:
        return StreamingHttpResponse(
            streaming_content=response.iter_content(2 ** 12),
            content_type=content_type,
            status=response.status_code,
            reason=response.reason,
        )

catchall_prod = TemplateView.as_view(template_name='index.html')

catchall = catchall_dev if settings.DEBUG else catchall_prod

assignment/core/views.py
import os

import pandas as pd
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render
from django.template.response import TemplateResponse
from django.views.generic import View

from .forms import FileUploadForm


class HomeView(View):
    template_name = 'core/home.html'

    def get(self, request, *args, **kwargs):
        if request.GET.get('ic-request'):
            self.template_name = 'core/home_content.html'
        return TemplateResponse(template=self.template_name, request=request)


class FileUploadView(View):
    template_name = 'core/upload.html'
    form_class = FileUploadForm

    def get(self, request, *args, **kwargs):
        context = {}
        if request.GET.get('ic-request'):
            self.template_name = 'core/upload_form.html'
        if 'file_path' in request.session and os.path.exists(request.session.get('file_path')):
            data = pd.read_csv(request.session.get('file_path'))
            context['df_table'] = data.to_html(escape=True,
                                               classes=["table-bordered", "table-striped", "table-hover",
                                                        "table-responsive"])
        return render(request, self.template_name, {'form': self.form_class, **context})

    def post(self, request, *args, **kwargs):
        context = {}
        if request.FILES.get('file'):
            # using FileSystemStorage to keep things simple for demonstration
            file = request.FILES.get('file')
            fs = FileSystemStorage()
            file_path = fs.save(file.name, file)
            data = pd.read_csv(file_path)
            request.session['file_path'] = file_path
        context['df_table'] = data.to_html(escape=True,
                                           classes=["table-bordered", "table-striped", "table-hover",
                                                    "table-responsive"])
        return render(request, 'core/csv_table.html', context)


class EntryFormView(View):
    template_name = 'core/entry_form.html'

    def get(self, request, *args, **kwargs):
        if request.GET.get('ic-request'):
            self.template_name = 'core/entry_form_content.html'
        return TemplateResponse(template=self.template_name, request=request)

datapane-test/app/views/csv.py
from django.http import HttpResponse, FileResponse
from django.views.generic import TemplateView, ListView
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.core.files.storage import FileSystemStorage

UPLOAD_DIRECTORY = 'uploads/'

@method_decorator(csrf_exempt, name='dispatch')
class CSVUploaderView(TemplateView):
    template_name = "csv_upload.html"

    def get_upload_dir(self, file_name):
        return UPLOAD_DIRECTORY+file_name

    def post(self, request, *args, **kwargs):
        if request.FILES.get('file'):
            uploaded_file = request.FILES.get('file')
            fs = FileSystemStorage()

            filename = fs.save(self.get_upload_dir(uploaded_file.name), uploaded_file)
            return FileResponse(open(filename, 'rb'))
        return HttpResponse("no file included in the request")

datapane-test/app/views/home.py
from django.views.generic import TemplateView, ListView

class HomeView(TemplateView):
    template_name = "index.html"

assignment/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Datapane</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://intercoolerjs.org/release/intercooler-1.2.3.min.js"></script>
</head>
<body>
{% include 'core/navbar.html' %}
<div id="content">
{% block content %}
{% endblock %}
</div>
</body>
</html>

assignment/core/templates/core/csv_table.html
{{ df_table | safe}}

assignment/core/templates/core/entry_form.html
{% extends 'core/base.html' %}
{% block content %}
{% include 'core/entry_form_content.html' %}
{% endblock %}

assignment/core/templates/core/entry_form_content.html
{% load render_bundle from webpack_loader %}
<h3>The form and table below is in React</h3>
<div id="entry_form_table"></div>
{% render_bundle "main" %}

assignment/core/templates/core/home.html
{% extends 'core/base.html' %}
{% block content %}
{% include 'core/home_content.html' %}
{% endblock %}

assignment/core/templates/core/home_content.html
<h4>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
    aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
    sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</h4>
<h5>The above text is from a django template.</h5>

assignment/core/templates/core/navbar.html
<nav class="navbar navbar-expand-sm bg-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a ic-push-url='true' ic-get-from="{% url 'core:home' %}" ic-target="#content" class="nav-link"
               href="{% url 'core:home' %}">Home</a>
        </li>
        <li class="nav-item">
            <a ic-push-url='true' ic-get-from="{% url 'core:upload' %}" ic-target="#content" class="nav-link"
               href="{% url 'core:upload' %}">CSV Uploader</a>
        </li>
        <li class="nav-item">
            <a ic-push-url='true' ic-get-from="{% url 'core:entry' %}" ic-target="#content" class="nav-link"
               href="{% url 'core:entry' %}">Entry Form</a>
        </li>
    </ul>
</nav>

assignment/core/templates/core/upload.html
{% extends 'core/base.html' %}
{% block content %}
{% include 'core/upload_form.html' %}
{% endblock %}

assignment/core/templates/core/upload_form.html
{% load bootstrap4 %}
<h3>Hello I am a Django form</h3>
<form method="post" enctype="multipart/form-data" ic-post-to="{% url 'core:upload' %}" ic-target="#df-table">
{% csrf_token %}
{% bootstrap_form form %}
{% bootstrap_button "Upload" button_type="submit" button_class="btn-primary" %}
</form>
<div id="df-table">
{% if df_table %}
{% include 'core/csv_table.html' %}
{% endif %}
</div>